config/routes.rb
Rails.application.routes.draw do
  get 'pages/index'

  root 'pages#index'

  get 'books/:id' => 'pages#book_check_out', as: :book_check_out

  post 'books/:id' => 'pages#check_out', as: :check_out

  get 'checkin' => 'pages#book_check_in'
  post 'checkin' => 'pages#check_in'

end

app/models/book.rb
class Book < ActiveRecord::Base
  has_many :checkouts
  has_many :patrons, :through => :checkouts
end

app/models/checkout.rb
class Checkout < ActiveRecord::Base
  belongs_to :book
  belongs_to :patron

end

app/models/patron.rb
class Patron < ActiveRecord::Base
  has_many :checkouts
  has_many :books, :through => :checkouts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    @books = Book.all
    @patrons = Patron.all
  end

  def book_check_out
    @checkout = Checkout.new
    if params[:id]
        @checkout.book = Book.find(params[:id])
    end
  end


  def check_out
    @checkout = Checkout.new(params.require(:checkout).permit(:book_id, :patron_id))
    if @checkout.save
      @checkout.book.update(is_checked_out: true)
      redirect_to root_path, notice: "BOOM"
    else
      render :book_check_out
    end
#    return @book.is_checked_out = !@book.is_checked_out
  end

  def book_check_in
        @books = Book.where(is_checked_out: true).pluck(:id)
        @checkouts = Checkout.where(book_id: @books)
  end

  def check_in
    @book = Book.find(params[:book_id])
    if @book
      @book.is_checked_out = false
      @book.save
      redirect_to checkin_path, notice: "Checkin successful"
    else
      render :checkin_path
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mylibrary</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pages/book_check_in.html.erb
<h1>
  List of books checked out: </h1>

<table>
  <thead>
    <tr>
      <th>Book Title </th>
      <th> Checked out to </th>
    </tr>
  </thead>
  <tbody>
    <% @checkouts.each do |c| %>
    <tr>
        <td><%= c.book.name %></td>
        <td><%= c.patron.name %>
        <td><%= link_to "Checkin", checkin_path(book_id:c.book.id), method: :post %></td>
      </tr>
      <% end %>
  </tbody>
</table>
<h3>
  <%= link_to "Home", root_path %>

</h3>

app/views/pages/book_check_out.html.erb
<%= form_for @checkout, url: check_out_path do |f| %>
<div>
<%= f.label "Book Title:  " %>
<%= f.collection_select :book_id, Book.all, :id, :name  %>
</div>


<div>
  <%= f.label "Patron's name: " %>

  <%= f.collection_select :patron_id, Patron.all, :id, :name  %>

</div>
  <%= f.submit "check out" %>
<% end %>

app/views/pages/check_out_page.html.erb
  <h1> Check Out Info</h1>
  <div><%= @book.name %></div>
  <div><%= @patron.name %></div>

  <%= f.label "Book checked out: " %>
 <%= @book.is_checked_out %></p>

  <%= link_to "Home", root_path %>

<% end %>

app/views/pages/index.html.erb
<center>
  <h1> List of Books
</h1>


<table>
  <thead>
    <tr>
      <th>Book Title </th>
      <th> Available </th>
    </tr>
  </thead>
  <tbody>
    <% @books.each do |book| %>
    <tr>
        <td><%= book.name %></td>
        <td><%= !book.is_checked_out %>

        <% if !book.is_checked_out? %>
        <td><%= link_to "Checkout", book_check_out_path(book) %></td>
        <% end %>
      </tr>
      <% end %>
  </tbody>
</table>

<h1>
  <%= link_to "Check-in a book", checkin_path %>

</h1>
</center>